### PR TITLE
Removes ObjectStore subscriber if not found in SubscriptionManager

### PR DESCRIPTION
**Pull request by flovilmart**
In UpdateChannel.pushUpdates, when queries mutate base on state parameters, some old ObjectStore subscriptions are still set but the `SubscriptionManager.getSubscription(subscribers[i]);` returns null.

The pushUpdate method crashes stack and prevent any further processing.

```
observe: function(props, state) {
    var q = (new Parse.Query(props.parseClassName))
        .descending('updatedAt')
    if (this.props.paginated) {
        q.skip(state.offset)
            .limit(state.limit)
    };

    if (state.filter) { 
      q.contains(this.props.display_key, state.filter);
    }
    return {
      items: q
    };
  }
```

As stated above, my filter function changes with the state.filter, offsets, and limit

### CODE REVIEW

**Comment by flovilmart** [comment]
@andrewimm I got no confirmation whatsoever I'm registered to the CLA. But that seems to be ok. LMK if there's anything else.

**Comment by andrewimm** [comment]
@flovilmart I'm currently trying to investigate what's going wrong to cause this in the first place. Rather than fix the subscriptions in `pushUpdate`, I'd like to track down where subscriptions are getting orphaned. There are similar issues happening with #59.

**Comment by flovilmart** [comment]
@andrewimm I'd definitely go the same approach as you. Still, orphaned subscription shouldn't prevent proper execution. And there's no way to trap the exception without a try-catch...

**Comment by andrewimm** [comment]
I originally put an exception there because it's a violation of the application invariant -- it should never happen, so it shouldn't need to be caught. It indicates a severe problem in subscription management. Same is true of orphaned subscriptions: I'd rather have them break execution, because they shouldn't happen in the first place. Silent errors are far more worrisome to me.

**Comment by flovilmart** [comment]
As you can see in my case, a simple state based paging is likely to break the lib. 

Do you want me to give you access to the code base? If you have a private repo I can push to, I can push my code.

**Comment by andrewimm** [comment]
I think I tracked down the issue: subscriptions that were destroyed did not notify the objects in their result sets. When these objects updated, they attempted to send an update to a nonexistent subscription. I'm releasing 0.3.1 to fix this, it should avoid this issue.

**Comment by flovilmart** [comment]
That seems to make sense. The pagination effectively can destroy subscriptions.

**Pull request closed without merging**
